FROM nvcr.io/nvidia/tensorrt:23.06-py3
WORKDIR /app

COPY requirements.txt /app/
RUN apt-get update && apt-get install -y  libsm6 libxext6 libfontconfig1 libxrender1 libgl1-mesa-glx 
RUN pip install --upgrade pip
RUN pip install  -r requirements.txt
RUN pip install onnx onnxruntime-gpu